[package]
name = "tina"
version = "0.1.0"
authors = ["wafrelka <wafrelka@gmail.com>"]

[dependencies]
oauthcli = "1.0"
url = "1.2"
yaml-rust = "0.3"
hyper = "0.9"
chrono = "0.2"
rust-crypto = "0.2"
csv = "0.14"
rand = "0.3"
