[package]
name = "tina"
version = "0.1.0"
authors = ["wafrelka <wafrelka@gmail.com>"]

[dependencies]
oauthcli = "1.0"
url = "1.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.7"
hyper = "0.9"
chrono = "0.2"
rust-crypto = "0.2"
csv = "0.14"
rand = "0.3"
log = "0.3"
log4rs = { version = "0.4", features = ["yaml"] }
