[package]
name = "tina"
version = "0.1.0"
authors = ["wafrelka <wafrelka@gmail.com>"]

[dependencies]
oauthcli = "0.1"
url = "1.1"
yaml-rust = "0.3"
hyper = "0.8"
chrono = "0.2"
rust-crypto = "0.2"
csv = "0.14"
